{
 "title": "Casita Peluchitos",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Current Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  source AS metric,\n  value/10\nFROM temp_sensors\nWHERE\n  $__timeFilter(time) AND\n  units = 'celsius' AND\n  scale = 10\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  source AS metric,\n  avg(value)/10\nFROM temp_sensors\nWHERE\n  scale = 10 AND\n  units = 'celsius'\nGROUP BY 1, source,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Current Relative Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  source AS metric,\n  value/10\nFROM humidity_sensors\nWHERE\n  $__timeFilter(time) AND\n  units = 'percentage' AND\n  scale = 10\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  source AS metric,\n  avg(value)/10\nFROM humidity_sensors\nWHERE\n  scale = 10 AND\n  units = 'percentage'\nGROUP BY 1, source,2\nORDER BY 1,2"
    }
   ]
  }
 ]
}